package io.testproject.generated.tests.onefi;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.AndroidDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.AndroidTest;
import io.testproject.java.sdk.v2.tests.helpers.AndroidTestHelper;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: onefi
 * Test: Airtime Recharge
 * Generated by: Ituraoluwa Owoeye (yemigr8t@gmail.com)
 * Generated on Wed Sep 25 12:49:10 GMT 2019.
 */
@Test(
    name = "Airtime Recharge",
    description = "paylater application",
    version = "1.0"
)
public class AirtimeRecharge implements AndroidTest {
  public ExecutionResult execute(AndroidTestHelper helper) throws FailureException {
    AndroidDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;

    // 1. Reset App
    //    Clear application data and restart (Auto-generated)
    booleanResult = driver.testproject().resetApp();
    report.step("Reset App", booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Tap 'Carbon up!'
    by = By.id("com.lenddo.mobile.paylater.staging:id/carbonUpButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Carbon up!'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Tap 'Skip'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tutorial_skip");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Skip'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Tap 'ALLOW'
    by = By.id("com.android.packageinstaller:id/permission_allow_button");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ALLOW'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Tap 'Sign In'
    by = By.id("com.lenddo.mobile.paylater.staging:id/user_type_existing");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign In'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Tap 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Type '08990001099' in 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().typeText(by,"08990001099");
    report.step("Type '08990001099' in 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 8. Make a Swipe gesture from ('682','580') to ('668','242')
    booleanResult = driver.testproject().swipeGesture(795,682,580,668,242);
    report.step("Make a Swipe gesture from ('682','580') to ('668','242')", booleanResult, TakeScreenshotConditionType.Failure);

    // 9. Tap '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 10. Type '1234' in '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().typeText(by,"1234");
    report.step("Type '1234' in '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 11. Tap 'Sign in1'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_next");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign in1'", booleanResult, TakeScreenshotConditionType.Failure);

    // 12. Tap 'Not right now'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tvRightNow");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Not right now'", booleanResult, TakeScreenshotConditionType.Failure);

    // 13. Tap 'ANDROID.WIDGET.RELATIVELAYOUT'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.support.v4.widget.DrawerLayout[1]/android.view.ViewGroup[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[3]/android.widget.LinearLayout[1]/android.support.v7.widget.RecyclerView[1]/android.widget.RelativeLayout[1]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.RELATIVELAYOUT'", booleanResult, TakeScreenshotConditionType.Failure);

    // 14. Tap 'ANDROID.WIDGET.LINEARLAYOUT2'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.support.v4.widget.DrawerLayout[1]/android.widget.LinearLayout[1]/android.view.ViewGroup[1]/android.support.v4.view.ViewPager[1]/android.widget.ScrollView[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.support.v7.widget.RecyclerView[1]/android.widget.LinearLayout[1]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.LINEARLAYOUT2'", booleanResult, TakeScreenshotConditionType.Failure);

    // 15. Tap 'Next1'
    by = By.id("com.lenddo.mobile.paylater.staging:id/button_next");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Next1'", booleanResult, TakeScreenshotConditionType.Failure);

    // 16. Tap 'com.lenddo.mobile.paylater.staging:id/walletRadioButton'
    by = By.id("com.lenddo.mobile.paylater.staging:id/walletRadioButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/walletRadioButton'", booleanResult, TakeScreenshotConditionType.Failure);

    // 17. Tap 'com.lenddo.mobile.paylater.staging:id/button_confirm_payment'
    by = By.id("com.lenddo.mobile.paylater.staging:id/button_confirm_payment");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/button_confirm_payment'", booleanResult, TakeScreenshotConditionType.Failure);

    // 18. Tap 'Securely pay ₦ 100.00'
    by = By.id("com.lenddo.mobile.paylater.staging:id/button_text_secure_pay");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Securely pay ₦ 100.00'", booleanResult, TakeScreenshotConditionType.Failure);

    // 19. Tap 'ANDROID.WIDGET.FRAMELAYOUT'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.ScrollView[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.FRAMELAYOUT'", booleanResult, TakeScreenshotConditionType.Failure);

    // 20. Tap 'ANDROID.WIDGET.FRAMELAYOUT2'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.ScrollView[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[2]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.FRAMELAYOUT2'", booleanResult, TakeScreenshotConditionType.Failure);

    // 21. Tap 'ANDROID.WIDGET.FRAMELAYOUT3'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.ScrollView[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[3]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.FRAMELAYOUT3'", booleanResult, TakeScreenshotConditionType.Failure);

    // 22. Tap 'ANDROID.WIDGET.FRAMELAYOUT4'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.ScrollView[1]/android.widget.FrameLayout[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[4]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.FRAMELAYOUT4'", booleanResult, TakeScreenshotConditionType.Failure);

    // 23. Tap 'Go back home'
    by = By.id("com.lenddo.mobile.paylater.staging:id/success_home_button");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Go back home'", booleanResult, TakeScreenshotConditionType.Failure);

    // 24. Tap 'Okay'
    by = By.id("com.lenddo.mobile.paylater.staging:id/okayButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Okay'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
