package io.testproject.generated.tests.onefi;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.AndroidDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.AndroidTest;
import io.testproject.java.sdk.v2.tests.helpers.AndroidTestHelper;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: onefi
 * Test: Fund Wallet
 * Generated by: Ituraoluwa Owoeye (yemigr8t@gmail.com)
 * Generated on Wed Sep 25 13:24:31 GMT 2019.
 */
@Test(
    name = "Fund Wallet",
    description = "onefi payment app",
    version = "1.0"
)
public class FundWallet implements AndroidTest {
  public ExecutionResult execute(AndroidTestHelper helper) throws FailureException {
    AndroidDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;

    // 1. Reset App
    //    Clear application data and restart (Auto-generated)
    booleanResult = driver.testproject().resetApp();
    report.step("Reset App", booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Tap 'Carbon up!'
    by = By.id("com.lenddo.mobile.paylater.staging:id/carbonUpButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Carbon up!'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Tap 'Skip'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tutorial_skip");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Skip'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Tap 'ALLOW'
    by = By.id("com.android.packageinstaller:id/permission_allow_button");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ALLOW'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Tap 'Sign In'
    by = By.id("com.lenddo.mobile.paylater.staging:id/user_type_existing");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign In'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Tap 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Type '08990001099' in 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().typeText(by,"08990001099");
    report.step("Type '08990001099' in 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 8. Make a Swipe gesture from ('646','523') to ('646','295')
    booleanResult = driver.testproject().swipeGesture(767,646,523,646,295);
    report.step("Make a Swipe gesture from ('646','523') to ('646','295')", booleanResult, TakeScreenshotConditionType.Failure);

    // 9. Tap '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 10. Type '1234' in '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().typeText(by,"1234");
    report.step("Type '1234' in '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 11. Tap 'Sign in1'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_next");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign in1'", booleanResult, TakeScreenshotConditionType.Failure);

    // 12. Tap 'Not right now'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tvRightNow");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Not right now'", booleanResult, TakeScreenshotConditionType.Failure);

    // 13. Tap 'com.lenddo.mobile.paylater.staging:id/fundWalletButton'
    by = By.id("com.lenddo.mobile.paylater.staging:id/fundWalletButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/fundWalletButton'", booleanResult, TakeScreenshotConditionType.Failure);

    // 14. Tap 'Fund with debit/ATM card'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[2]/android.widget.TextView[1]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Fund with debit/ATM card'", booleanResult, TakeScreenshotConditionType.Failure);

    // 15. Tap '0.00'
    by = By.id("com.lenddo.mobile.paylater.staging:id/walletAmountToFund");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap '0.00'", booleanResult, TakeScreenshotConditionType.Failure);

    // 16. Type '1000' in '0.00'
    by = By.id("com.lenddo.mobile.paylater.staging:id/walletAmountToFund");
    booleanResult = driver.testproject().typeText(by,"1000");
    report.step("Type '1000' in '0.00'", booleanResult, TakeScreenshotConditionType.Failure);

    // 17. Tap at ('668','1141') with '1' fingers for '100'ms
    booleanResult = driver.testproject().tapGestureAtCoordinates(668,1141,1,100);
    report.step("Tap at ('668','1141') with '1' fingers for '100'ms", booleanResult, TakeScreenshotConditionType.Failure);

    // 18. Tap 'Proceed'
    by = By.id("com.lenddo.mobile.paylater.staging:id/proceedWalletFunding");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Proceed'", booleanResult, TakeScreenshotConditionType.Failure);

    // 19. Tap 'com.lenddo.mobile.paylater.staging:id/image_check'
    by = By.id("com.lenddo.mobile.paylater.staging:id/image_check");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/image_check'", booleanResult, TakeScreenshotConditionType.Failure);

    // 20. Tap 'com.lenddo.mobile.paylater.staging:id/button_confirm_payment'
    by = By.id("com.lenddo.mobile.paylater.staging:id/button_confirm_payment");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/button_confirm_payment'", booleanResult, TakeScreenshotConditionType.Failure);

    // 21. Tap 'Securely pay ₦ 100.00'
    by = By.id("com.lenddo.mobile.paylater.staging:id/button_text_secure_pay");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Securely pay ₦ 100.00'", booleanResult, TakeScreenshotConditionType.Failure);

    // 22. Tap 'Go back home'
    by = By.id("com.lenddo.mobile.paylater.staging:id/success_home_button");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Go back home'", booleanResult, TakeScreenshotConditionType.Failure);

    // 23. Tap 'Okay'
    by = By.id("com.lenddo.mobile.paylater.staging:id/okayButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Okay'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
