package io.testproject.generated.tests.onefi;

import io.testproject.java.execution.results.StepExecutionResult;
import io.testproject.java.sdk.v2.Runner;
import java.lang.Exception;
import java.lang.String;

/**
 * This class was automatically generated by TestProject
 * Provides an example how to run coded TestProject tests
 */
public class onefiRunner {
  public static String developerToken = "1xXxhH8FX3gvk2Sktpwci9NR363Ex8ItSLs2TxRAgnA";

  public static String deviceUdid = "0238110770400613";

  public static String androidPackage = "com.lenddo.mobile.paylater.staging";

  public static String androidName = "com.lenddo.mobile.paylater.home.activity.SplashScreenActivity";

  public static void main(String[] args) {
    try {
      runFundWallet();
    }
    catch (Exception e) {
    }
  }

  /**
   * Runs "FundWallet"
   */
  public static StepExecutionResult runFundWallet() throws Exception {
    Runner runner = Runner.createAndroid(developerToken,deviceUdid,androidPackage,androidName);
    return runner.run(new FundWallet(), true);
  }
}
