package io.testproject.generated.tests.onefi;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.AndroidDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.AndroidTest;
import io.testproject.java.sdk.v2.tests.helpers.AndroidTestHelper;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: onefi
 * Test: Sign-in
 * Generated by: Ituraoluwa Owoeye (yemigr8t@gmail.com)
 * Generated on Wed Sep 25 06:19:02 GMT 2019.
 */
@Test(
    name = "Sign-in",
    description = "paylater onefi",
    version = "1.0"
)
public class SignIn implements AndroidTest {
  public ExecutionResult execute(AndroidTestHelper helper) throws FailureException {
    AndroidDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;

    // 1. Reset App
    //    Clear application data and restart (Auto-generated)
    booleanResult = driver.testproject().resetApp();
    report.step("Reset App", booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Tap 'Carbon up!'
    by = By.id("com.lenddo.mobile.paylater.staging:id/carbonUpButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Carbon up!'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Tap 'Skip'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tutorial_skip");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Skip'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Tap 'ALLOW'
    by = By.id("com.android.packageinstaller:id/permission_allow_button");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ALLOW'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Tap 'Sign In'
    by = By.id("com.lenddo.mobile.paylater.staging:id/user_type_existing");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign In'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Tap 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Type '08990001099' in 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().typeText(by,"08990001099");
    report.step("Type '08990001099' in 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 8. Make a Swipe gesture from ('658','626') to ('653','367')
    booleanResult = driver.testproject().swipeGesture(817,658,626,653,367);
    report.step("Make a Swipe gesture from ('658','626') to ('653','367')", booleanResult, TakeScreenshotConditionType.Failure);

    // 9. Tap '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 10. Type '1234' in '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().typeText(by,"1234");
    report.step("Type '1234' in '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 11. Tap 'Sign in1'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_next");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign in1'", booleanResult, TakeScreenshotConditionType.Failure);

    // 12. Tap 'Not right now'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tvRightNow");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Not right now'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
