package io.testproject.generated.tests.onefi;

import io.testproject.java.annotations.v2.Test;
import io.testproject.java.enums.TakeScreenshotConditionType;
import io.testproject.java.sdk.v2.drivers.AndroidDriver;
import io.testproject.java.sdk.v2.enums.ExecutionResult;
import io.testproject.java.sdk.v2.exceptions.FailureException;
import io.testproject.java.sdk.v2.reporters.TestReporter;
import io.testproject.java.sdk.v2.tests.AndroidTest;
import io.testproject.java.sdk.v2.tests.helpers.AndroidTestHelper;
import org.openqa.selenium.By;

/**
 * This class was automatically generated by TestProject
 * Project: onefi
 * Test: Wallet Transaction filter
 * Generated by: Ituraoluwa Owoeye (yemigr8t@gmail.com)
 * Generated on Wed Sep 25 13:23:21 GMT 2019.
 */
@Test(
    name = "Wallet Transaction filter",
    description = "paylater payment app",
    version = "1.0"
)
public class WalletTransactionFilter implements AndroidTest {
  public ExecutionResult execute(AndroidTestHelper helper) throws FailureException {
    AndroidDriver driver = helper.getDriver();
    // set timeout for driver actions (similar to step timeout)
    driver.setTimeout(15000);
    TestReporter report = helper.getReporter();
    By by;
    boolean booleanResult;

    // 1. Reset App
    //    Clear application data and restart (Auto-generated)
    booleanResult = driver.testproject().resetApp();
    report.step("Reset App", booleanResult, TakeScreenshotConditionType.Failure);

    // 2. Tap 'Carbon up!'
    by = By.id("com.lenddo.mobile.paylater.staging:id/carbonUpButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Carbon up!'", booleanResult, TakeScreenshotConditionType.Failure);

    // 3. Tap 'Skip'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tutorial_skip");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Skip'", booleanResult, TakeScreenshotConditionType.Failure);

    // 4. Tap 'ALLOW'
    by = By.id("com.android.packageinstaller:id/permission_allow_button");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ALLOW'", booleanResult, TakeScreenshotConditionType.Failure);

    // 5. Tap 'Sign In'
    by = By.id("com.lenddo.mobile.paylater.staging:id/user_type_existing");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign In'", booleanResult, TakeScreenshotConditionType.Failure);

    // 6. Tap 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 7. Type '08990001099' in 'Phone number'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_phone");
    booleanResult = driver.testproject().typeText(by,"08990001099");
    report.step("Type '08990001099' in 'Phone number'", booleanResult, TakeScreenshotConditionType.Failure);

    // 8. Make a Swipe gesture from ('649','611') to ('630','266')
    booleanResult = driver.testproject().swipeGesture(769,649,611,630,266);
    report.step("Make a Swipe gesture from ('649','611') to ('630','266')", booleanResult, TakeScreenshotConditionType.Failure);

    // 9. Tap '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 10. Type '1234' in '1234'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_pin");
    booleanResult = driver.testproject().typeText(by,"1234");
    report.step("Type '1234' in '1234'", booleanResult, TakeScreenshotConditionType.Failure);

    // 11. Tap 'Sign in1'
    by = By.id("com.lenddo.mobile.paylater.staging:id/sign_in_next");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Sign in1'", booleanResult, TakeScreenshotConditionType.Failure);

    // 12. Tap 'Not right now'
    by = By.id("com.lenddo.mobile.paylater.staging:id/tvRightNow");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Not right now'", booleanResult, TakeScreenshotConditionType.Failure);

    // 13. Tap 'com.lenddo.mobile.paylater.staging:id/viewWalletTransactionsButton'
    by = By.id("com.lenddo.mobile.paylater.staging:id/viewWalletTransactionsButton");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/viewWalletTransactionsButton'", booleanResult, TakeScreenshotConditionType.Failure);

    // 14. Tap 'com.lenddo.mobile.paylater.staging:id/transactionTypeSpinner'
    by = By.id("com.lenddo.mobile.paylater.staging:id/transactionTypeSpinner");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/transactionTypeSpinner'", booleanResult, TakeScreenshotConditionType.Failure);

    // 15. Tap 'Wallet'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.ListView[1]/android.widget.TextView[2]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Wallet'", booleanResult, TakeScreenshotConditionType.Failure);

    // 16. Tap 'ANDROID.WIDGET.RELATIVELAYOUT1'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.support.v4.widget.DrawerLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.support.v4.view.ViewPager[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.view.ViewGroup[1]/android.support.v7.widget.RecyclerView[1]/android.widget.LinearLayout[1]/android.support.v7.widget.RecyclerView[1]/android.widget.RelativeLayout[1]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.RELATIVELAYOUT1'", booleanResult, TakeScreenshotConditionType.Failure);

    // 17. Tap 'com.lenddo.mobile.paylater.staging:id/ivBack'
    by = By.id("com.lenddo.mobile.paylater.staging:id/ivBack");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/ivBack'", booleanResult, TakeScreenshotConditionType.Failure);

    // 18. Tap 'com.lenddo.mobile.paylater.staging:id/transactionTypeSpinner'
    by = By.id("com.lenddo.mobile.paylater.staging:id/transactionTypeSpinner");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/transactionTypeSpinner'", booleanResult, TakeScreenshotConditionType.Failure);

    // 19. Tap 'Airtime'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.FrameLayout[1]/android.widget.ListView[1]/android.widget.TextView[4]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'Airtime'", booleanResult, TakeScreenshotConditionType.Failure);

    // 20. Tap 'ANDROID.WIDGET.RELATIVELAYOUT1'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.support.v4.widget.DrawerLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.support.v4.view.ViewPager[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.view.ViewGroup[1]/android.support.v7.widget.RecyclerView[1]/android.widget.LinearLayout[1]/android.support.v7.widget.RecyclerView[1]/android.widget.RelativeLayout[1]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'ANDROID.WIDGET.RELATIVELAYOUT1'", booleanResult, TakeScreenshotConditionType.Failure);

    // 21. Tap 'com.lenddo.mobile.paylater.staging:id/ivBack'
    by = By.id("com.lenddo.mobile.paylater.staging:id/ivBack");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/ivBack'", booleanResult, TakeScreenshotConditionType.Failure);

    // 22. Tap 'com.lenddo.mobile.paylater.staging:id/title_up'
    by = By.id("com.lenddo.mobile.paylater.staging:id/title_up");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'com.lenddo.mobile.paylater.staging:id/title_up'", booleanResult, TakeScreenshotConditionType.Failure);

    // 23. Tap 'MTN - IN_PROGRESS . 01:48 PM'
    by = By.xpath("//android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.support.v4.widget.DrawerLayout[1]/android.widget.LinearLayout[1]/android.widget.FrameLayout[1]/android.view.ViewGroup[1]/android.support.v4.view.ViewPager[1]/android.widget.LinearLayout[1]/android.widget.LinearLayout[1]/android.view.ViewGroup[1]/android.support.v7.widget.RecyclerView[1]/android.widget.LinearLayout[1]/android.support.v7.widget.RecyclerView[1]/android.widget.RelativeLayout[1]/android.widget.LinearLayout[1]/android.widget.TextView[2]");
    booleanResult = driver.testproject().tap(by);
    report.step("Tap 'MTN - IN_PROGRESS . 01:48 PM'", booleanResult, TakeScreenshotConditionType.Failure);

    return ExecutionResult.PASSED;
  }
}
